package Logica;
import Excepciones.*;
import LogicaDTO.*;
import java.util.List;
import java.util.Set;
import javax.swing.tree.DefaultMutableTreeNode;

public interface IControllerMusica { 
    public abstract void altaAlbum(DTOAlbum album, Set<DTOTema> temas) throws AlbumYaExisteException, UsuarioNoExisteException;   
    public abstract void AltaGenero (String nombregen, String nombrepadre) throws GenroYaExiste;
    public abstract void altaListaReproduccion(String nombre, String genero, String duenio, String ruta, boolean privada)throws ListaYaExisteException, GeneroNoExiste;
    public void publicarLista(String nombreUsuario, String nombreLista) throws UsuarioNoExisteException, ListaNoexisteException, OperacionNoPermitidaException, ListaYaEsPublicaException;
    //public abstract void AgregarTemaLista(String nombreusuario,String nombrelista, String nombretema)throws UsuariosNoExisten, ListaNoexisteException,NoesDueñodelaLista, TemaNoExiste;
    public abstract DefaultMutableTreeNode DameTodoslosgeneros();
    public abstract void EliminoGenero(String nombregen);
    public abstract List<String> obtenerAlbumsPorGenero(String generoSeleccionado);
    public abstract List<String> obtenerAlbumsPorArtista(String artistaSeleccionado);
    public abstract DTOAlbum consultaAlbumPorTitulo(String albumSeleccionado);
    public abstract boolean existeAlbum(String nicknameArtista, String titulo);
    public  abstract List <DTOGenero> Datageneros();
    public  abstract void AñadotemalistaAlbum(String nombreAlbum, String nombreLista, String nombreTema, String NombreUsuario);
    public abstract void aniadoTemaListaPublica(String nombreLista, String nombreTema,String nombreAlbum);
    public abstract List <DTOTema> TemasdeListas(String nombrelista);
    public abstract List<DTOLista> Obtengolistas()throws NoExisteLista;
    public abstract List<DTOLista> Obtengolistassinduenio()throws NoExisteLista;
    public abstract void aniadoTemaListaConduenio(String nombreUsuario,String nombrelista,String nombreteam,String nombreAlbum);
    public abstract List<DTOLista> Obtengolistasconduenio()throws NoExisteLista;
    public abstract List<DTOAlbum> ObtengoAlbums();
    public abstract List<DTOTema> ObtengoTemasdeAlbum(String nombreAlbum);
    public abstract void EliminotemaLista(String nombrelista, String nombretema, String nombreAlbum);
    public abstract void EliminoTemaListaConduenio(String nombreUsuario,String nombrelista,String nombreteam,String nombreAlbum);
    public abstract List<DTOTema> obtenerTemitas();
    public abstract List<DTOTema> obtenerTemitasDATA();
    public abstract List<DTOLista> ObtengoListasPublicas() throws NoExisteLista;
    public abstract List<DTOAlbum> obtenerAlbums();
    public abstract DTOLista consultaListaPorTituloyGenero(String listaSeleccionada, String genero);
    public abstract List<DTOTema> obtenerTemitasfavCliente(String nicknames);
    public abstract List<DTOLista> obtenerListitasfavCliente(String nicknames);
    public abstract List<DTOAlbum> obtenerAlbumsfavCliente(String nicknames);
    public abstract List<String> obtenerListaPorGenero(String generoSeleccionado);
    public abstract List<DTOLista> obtenerListaPorClienteDATA(String artistaSeleccionado);
    public abstract List<String> obtenerListaPorCliente(String artistaSeleccionado);
    public abstract DTOLista consultaListaPorTitulo(String listaSeleccionado);
    public abstract List<DTOLista> obtenerListitas();
    public abstract DTOTema consultaTemaPorTitulo(String temaSeleccionada);
    public abstract void aniadoTemaListaConduenioLista(String nombreUsuario,String nombrelista,String nombreteam,String nombrealb);
    public abstract void aniadoTemaListaPublicaLista(String nombrelista,String nombreteam,String nombrealb);
    public abstract List<DTOLista> obtenerListaPorGeneroDTOLISTA(String generoSeleccionado);
    public abstract List <DTOTema> TemasdeListasDTO(String nombrelista);
    public abstract List<DTOLista> ObtengoListasPublicasDATA() throws NoExisteLista;
    public abstract DTOLista ObtenerListaporTitulo(String nombrelista)throws NoExisteLista;
    public abstract DTOTema consultaTemaPorTituloYAlbum(String nombreTema, String nombreAlbum, String nombreArtista);
    public abstract List<String> obtenerNombresGeneros();
    public abstract List<DTOAlbum> obtenerTodosLosAlbums();
    public abstract boolean albumEsDeXGenero(String albumTitulo, String artistaNickname, String generoNombre);
    public abstract List<DTOTema> temasDelAlbum(String titulo);
    public abstract List<String> ObtengolistasClipriv(String nickcli)throws NoExisteLista;
    public abstract boolean existeGenero(String genero);
    public abstract boolean obtenerPadre(String nombreGenero);
    public abstract boolean espublicasiono(String nombreUsuario, String NombreLista);
    public abstract boolean sumaDescarga(DTOTema t);
    public abstract boolean sumaReproduccion(DTOTema t);
    public abstract List<DTOTema> promedioTemas(); 
    
}
